baseURL = "https://example.com/about"
languageCode = "en-us"
title = "Zoe Gadon-Thompson"
theme = "personal-web"
copyright="© Zoe Gadon-Thompson"
googleAnalytics = ""
enableEmoji=true
enableRobotsTXT=true
pygmentsUseClasses=true
pygmentsCodeFences=true

[params.intro]
  main = "Hi there, I'm Zoe :unicorn:"
  sub = "I'm a Software Engineer, Crocheter, FOSS nerd"

[taxonomies]
  design = "designs"
  tech = "techs"

[blackfriday]
  hrefTargetBlank = true

[params]
  breadcrumb = true
  accentColor = "#FD3519"
  mainSections = ['portfolio'] # values: ['post', 'portfolio'] only accept one section, to be displayed bellow 404

[params.notFound]
  gopher = "/images/gopher.png" # checkout https://gopherize.me/
  h1 = '404.'
  p = "It seems that this page doesn't exist."

[params.sections]
  # Define how your sections will be called
  # when automatically pulled. For instance in the 404 page
  post = "article"
  portfolio = "project"

[params.sidebar]
  backgroundImage = 'https://elestoque.org/wp-content/uploads/2019/05/astrocover.png'
  gradientOverlay = '' # default: rgba(0,0,0,0.4),rgba(0,0,0,0.4)
  logo = "https://pbs.twimg.com/profile_images/1221592196153069571/frDSxctM_400x400.jpg"
[params.assets]
  favicon = "https://pbs.twimg.com/profile_images/1221592196153069571/frDSxctM_400x400.jpg"
  customCSS = ""

[params.social]
  github = "https://github.com/gingerzoealex"
  twitter = "https://twitter.com/gingerzoealex"
  linkedin = "https://www.linkedin.com/in/zoe-gadon-thompson-b33776169/"
  medium = "https://medium.com/@gingerzoealex"

[params.contact]
  email = "zdb.aalexandra@gmail.com"
  text= "" # text of the contact link in the sidebar. If email params.contact.email is defined


[menu]

  [[menu.main]]
  identifier = "talks"
  name = "Talks"
  title = "Talks"
  url = "/talks/"
  weight = -110

  [[menu.main]]
  identifier = "cv"
  name = "CV"
  title = "CV"
  url = "/cv/"
  weight = -100

staticDir = ["static"]

[sitemap]
  changefreq = "monthly"
  filename = "sitemap.xml"
  priority = 0.5

[privacy]
  [privacy.googleAnalytics]
    anonymizeIP = true
    disable = true
    respectDoNotTrack = true
    useSessionStorage = false
  [privacy.twitter]
    disable = false
    enableDNT = true
    simple = false